### ISSUE TITLE
VIEW3D_PT_CustomMenuのbl_labelとbl_categoryの説明が逆

### ISSUE THREAD

**Issue by itashin0501** [nutti/Introduction-to-Addon-Development-in-Blender-Web#10]
|クラス変数|値の意味|
|---|---|
|```bl_label```|パネルに登録時にタイトルとして表示される文字列<br>ツール・シェルフに登録する場合はタブに表示される文字列となる|
|```bl_category```|ツール・シェルフのタブを開いたときに表示されるメニューのヘッダーに表示される文字列|

上記を下記に変更願います

 |クラス変数|値の意味|
 |---|---|
|```bl_category```|パネルに登録時にタイトルとして表示される文字列<br>ツール・シェルフに登録する場合はタブに表示される文字列となる|
|```bl_label```|ツール・シェルフのタブを開いたときに表示されるメニューのヘッダーに表示される文字列|

**Comment by nutti** [comment]
@itashin0501 

誤字のご報告、ありがとうございます。
ご報告していただいたのに大変申し訳ないのですが、GitBookがLegacyになっており、GitBookの更新が行えない状態です。
もしGitHubのみの修正でよろしければ、修正しますがいかがでしょうか？

**Comment by itashin0501** [comment]
返信ありがとうございます。
はい。GitHubのみの修正で結構です。
すごく参考にさせて頂いております。よろしくお願いします。

**Comment by nutti** [comment]
@itashin0501 

わかりました。これから修正します。
ところで以下に示していますように、誤字の報告などを行っていただいた方は、[謝辞](https://github.com/nutti/Introduction-to-Add-on-Development-in-Blender/blob/release/body/Conclusion.md#%E8%AC%9D%E8%BE%9E) のところに名前を掲載させていただくことが可能となっています。

https://github.com/nutti/Introduction-to-Add-on-Development-in-Blender#%E8%AA%A4%E5%AD%97%E8%84%B1%E5%AD%97%E3%82%92%E5%A0%B1%E5%91%8A%E3%81%84%E3%81%9F%E3%81%A0%E3%81%91%E3%82%8B%E6%96%B9%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

もし掲載を希望されるのであれば、掲載名（ニックネーム可）を教えていただければと思います。

**Comment by itashin0501** [comment]
名前の掲載案内ありがとうございます。
itashin0501
でお願いします。

**Comment by nutti** [comment]
@itashin0501 

報告ありがとうございました。修正しました。
また、itashin0501様を謝辞に追加させていただきました。
