### ISSUE TITLE
2-1 Blender APIのマウスオーバー時に関数名をコピーできる説明の追加要望

### ISSUE THREAD

**Issue by hzuika** [nutti/Introduction-to-Addon-Development-in-Blender-Web#11]
「はじめてのBlenderアドオン開発」を読ませていただいております。非常にわかりやすく、大変助かっています。ありがとうございます。

「2-1. アドオン開発の基礎を身につける」まで読み進めたのですが、こちらのBlender APIの確認方法について
**マウスオーバー時にCtrl+Cを押すことで、表示されているAPIの関数をコピーできる**
という説明を追加していただけますでしょうか。APIについて調べたり、自分のスクリプトに組み込む際に、有用な機能であると思います。

**Comment by nutti** [comment]
@hzuika 

情報提供＆本書への要望、ありがとうございました。
APIをコピー＆ペーストできる件、初耳でした。便利な機能ですね！

早速、本記述を追加させていただきました。
もし差し支えなければ、以下にお名前を載せていただければと思いますが、いかがでしょう？
https://colorful-pico.net/introduction-to-addon-development-in-blender/2.8/html/chapter_99/01_Conclusion.html

掲載をご希望でしたら、掲載するお名前（ハンドルネーム可）を教えていただけると助かります。
ご検討のほど、よろしくお願いいたします。

**Comment by hzuika** [comment]
@nutti 

早速の対応ありがとうございます。

名前掲載の件ですが
hzuika
で掲載していただけますと幸いです。

それでは、Blender内部構造に関する本も楽しみにしております。

**Comment by hzuika** [comment]
@nutti 

早速の対応ありがとうございます。

名前掲載の件ですが
hzuika
で掲載していただけますと幸いです。

それでは、Blender内部構造に関する本も楽しみにしております。

**Comment by hzuika** [comment]
@nutti 

早速の対応ありがとうございます。

名前掲載の件ですが
hzuika
で掲載していただけますと幸いです。

それでは、Blender内部構造に関する本も楽しみにしております。

**Comment by hzuika** [comment]
@nutti 

早速の対応ありがとうございます。

名前掲載の件ですが
hzuika
で掲載していただけますと幸いです。

それでは、Blender内部構造に関する本も楽しみにしております。

**Comment by hzuika** [comment]
@nutti 

早速の対応ありがとうございます。

名前掲載の件ですが
hzuika
で掲載していただけますと幸いです。

それでは、Blender内部構造に関する本も楽しみにしております。

**Comment by hzuika** [comment]
@nutti 

早速の対応ありがとうございます。

名前掲載の件ですが
hzuika
で掲載していただけますと幸いです。

それでは、Blender内部構造に関する本も楽しみにしております。

**Comment by hzuika** [comment]
@nutti 

早速の対応ありがとうございます。

名前掲載の件ですが
hzuika
で掲載していただけますと幸いです。

それでは、Blender内部構造に関する本も楽しみにしております。

**Comment by hzuika** [comment]
@nutti 

早速の対応ありがとうございます。

名前掲載の件ですが
hzuika
で掲載していただけますと幸いです。

それでは、Blender内部構造に関する本も楽しみにしております。

**Comment by hzuika** [comment]
@nutti 

早速の対応ありがとうございます。

名前掲載の件ですが
hzuika
で掲載していただけますと幸いです。

それでは、Blender内部構造に関する本も楽しみにしております。

**Comment by hzuika** [comment]
@nutti 

早速の対応ありがとうございます。

名前掲載の件ですが
hzuika
で掲載していただけますと幸いです。

それでは、Blender内部構造に関する本も楽しみにしております。

**Comment by hzuika** [comment]
@nutti 

早速の対応ありがとうございます。

名前掲載の件ですが
hzuika
で掲載していただけますと幸いです。

それでは、Blender内部構造に関する本も楽しみにしております。

**Comment by hzuika** [comment]
すみません。
どういうわけか、同じ内容のコメントが10件ほど連続で投稿されてしまいました。（すぐに削除いたしました。）

通知が大量に来てしまっているかもしれません。
申し訳ございません。

**Comment by nutti** [comment]
@hzuika 

ありがとうございます！
追加させていただきました。

今後も何かありましたら、よろしくお願いします（直接プルリク経由で修正依頼出していただいても構いません）。
