### ISSUE TITLE
コンソールをUTF-8にする方法について追記を希望

### ISSUE THREAD

**Issue by natukikazemizo** [nutti/Introduction-to-Addon-Development-in-Blender-Web#8]
はじめまして。N(Natukikazemizo)と申します。

nuttiさんの「はじめてのBlenderアドオン開発」読ませていただきました。
nuttiさんが書かれた内容は，私がアドオンを初めて開発するにあたり，大いに役に立ちそうです。

で，題記の件ですが，「はじめてのBlenderアドオン開発」に掲載されているアドオンがコンソールに出力するログは日本語になっています。Windows10環境の場合なにもしなかった場合，コンソールに出力されるログが文字化けしてしまします。この問題は，Windows10環境の場合，コンソールの文字コードをUTF-8にすることにより解決できるのですが，この原因を特定するのに私の場合は4時間程度かかりました。

nuttiさんの本をより分かりやすくするために，コンソールの文字コードをUTF-8にする方法について，追記していただけないでしょうか？

以上

**Comment by nutti** [comment]
コメントと改善案を提案いただき、ありがとうございます。

> Windows10環境の場合なにもしなかった場合，コンソールに出力されるログが文字化けしてしまします。この問題は，Windows10環境の場合，コンソールの文字コードをUTF-8にすることにより解決できるのですが，この原因を特定するのに私の場合は4時間程度かかりました

不十分な解説でご迷惑をおかけし、申し訳ありませんでした。
UTF-8に変更する記事を書き始めつつ書籍を掲載しているGitBookを確認したところ、大きく仕様が変更されたようで、現在掲載しているところがLegacyという位置づけになり、今後の更新に加えて公開継続すらも危うくなったことが発覚しました。
このため、更新した内容をすぐに反映できないという状況です。

しかし一方で、Blender 2.8も登場する予定ですし、この機会に1から本書を書き直そうかとも考えています。
このため大変申し訳ないのですが、該当箇所は次版発行時に追記させていただきたいです。

なおGitBookの状況を踏まえて、これまで第2版まで書籍で購入された方に限定してPDF版を提供しておりましたが、フリーで公開することも考えたいと思います。


追伸：書籍に関して改善案をご提示していただいた方は、書籍の最後に名前を掲載させていただく予定になっております。もし掲載名を教えていただければ、追加いたしますがいかがでしょうか？

**Comment by nutti** [comment]
@natukikazemizo 

GitBookはこれ以上更新ができないため、第2版についてはGitHubを最新版とすることに決めました。
そこで、ご指摘いただいたことを修正しようと考えているのですが、同じところで躓いてしまっています。もしご存知でしたら、教えていただけないでしょうか？

以前コンソールに日本語を出力した時には、`chcp 65001` を実行することで日本語出力が可能になったのですが、最近のWindowsではこれができなくなってしまっているようです。
現状Windowsでは、日本語出力を諦めかけているのですが、もし解決策をご存知でしたら教えていただけると非常に助かります。

**Comment by natukikazemizo** [comment]
@nutti
私の環境ではコマンドプロンプトでchcp 65001は動作しています。
Windows10 Pro 64bit Version:1803 OSビルド:17134.523
です。
具体的には

`chcp 65001`
`cd C:\Program Files\Blender Foundation\Blender\`
`.\blender.exe`

のバッチを作成して，それでBlenderを起動しています。

**Comment by nutti** [comment]
@natukikazemizo 

ご回答、ありがとうございます。
私の環境でうまく動作しなかったのは、コマンドプロンプトのフォントが日本語非対応であったようです。
動作確認が取れましたので、ドキュメントも修正しました。
ところで、下記の件はどうしましょうか？

> 書籍に関して改善案をご提示していただいた方は、書籍の最後に名前を掲載させていただく予定になっております。もし掲載名を教えていただければ、追加いたしますがいかがでしょうか？

**Comment by natukikazemizo** [comment]
@nutti 
問題解決よかったです。

名前の掲載の件はお願いします。
表記する名前は
N(Natukikazemizo)
でお願いします。

**Comment by nutti** [comment]
@natukikazemizo 

ありがとうございます。
名前を掲載させていただきました。
本件、すべて修正が完了していますので、クローズします。
